### ISSUE TITLE
🐛 Meta-Issue Tracker

### ISSUE THREAD

**Issue by MrAlex94** [MrAlex94/Waterfox#1630]
This is a new meta-issue tracker, as unfortunately GitHub does not allow changing ownership of issues.

From @Peacock365:

> _Hey there!_
> 
> _This is a list of Waterfox bugs yet unresolved. No guarantee for completeness. Should some of them be resolved by now, feel free to inform me. I will delete the corresponding entries in this case. This issue was created in an attempt to create an overview and as a potential starting point for sorting them out._

#### 🗝 Key
- [x] Completed
- [x] ~~Won't/Can't complete~~
- [ ] Pending

### Waterfox General
- [ ] Portable updater deleting inappropriately? 
- [ ] Build Waterfox on linux with static musl libc
- [ ] Add README to Linux tarball
- [x] ~~ANGLE -> MoltenVK for macOS~~
- [ ] Checksum for file downloads
- [ ] Revert Bug 606655
- [ ] libc++ for macOS builds (https://github.com/parrotgeek1/FirefoxLegacy)
- [ ] 1405031 - Support additional click events for browserAction and pageAction
- [x] https://github.com/MrAlex94/Waterfox/issues/1265
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1373490
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1419264
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1596894
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1419264
- [ ] Re-instate use of [WebCompat](https://github.com/mozilla/gecko-dev/tree/esr60/browser/extensions/webcompat) add-on to help fix website issues, including [UA](https://wiki.mozilla.org/Compatibility/Go_Faster_Addon/Override_Policies_and_Workflows#User_Agent_overrides)!

### Waterfox Classic

- [x] ~~Waterfox/Mac dictation bug https://github.com/MrAlex94/Waterfox/issues/85~~
- [ ] On Linux: .config/waterfox | https://github.com/MrAlex94/Waterfox/issues/243 | https://bugzilla.mozilla.org/show_bug.cgi?id=259356
- [x] ~~Extensions break on path change https://github.com/MrAlex94/Waterfox/issues/329~~
- [x] Program description on Windows misleading https://github.com/MrAlex94/Waterfox/issues/387
- [ ] Spellchecking bug https://github.com/MrAlex94/Waterfox/issues/374
- [ ] Autoshortening of hamburger menu fails | https://github.com/MrAlex94/Waterfox/issues/373
| **POSSIBLE SOLUTION**: https://bugzilla.mozilla.org/show_bug.cgi?id=1415921#c0
- [ ] Use unbiased pixelrounding for borders | https://github.com/MrAlex94/Waterfox/issues/422
| **POSSIBLE SOLUTION**: https://github.com/MoonchildProductions/Pale-Moon/commit/6d773b16968b50c848083382b03bd99727c08f41
- [ ] Some Firefox directories are still being created  https://github.com/MrAlex94/Waterfox/issues/405
- [ ] webRequest leak  https://github.com/MrAlex94/Waterfox/issues/414 | **POSSIBLE SOLUTIONS** | https://reviewboard.mozilla.org/r/237446/diff/7#index_header | https://hg.mozilla.org/mozilla-central/rev/ad061f4fec73#l2.75
- [ ] Waterfox "remembers" screensize tiling wm https://github.com/MrAlex94/Waterfox/issues/527
- [ ] Silently installed Mozilla add-ons | https://github.com/MrAlex94/Waterfox/issues/515
- [ ] Checkbox and radio pixelated when zoomed in https://github.com/MrAlex94/Waterfox/issues/433
- [ ] `Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[NSImage drawInRect:]: unrecognized selector sent to instance 0x136655880]`
- [ ] Plugin-container crash on macOS < 10.9
- [ ] Update H.264 profiles decoder
- [ ] 1580288 (Classic)
- [ ] 1560667 (Classic)
- [ ] 1218456 (Can be done, need time!) https://github.com/classilla/tenfourfox/commit/5e0cd430c22a7e93294c3b281d6893e17b1195fc#diff-f3f6fe3abe7e7f0ee20bf4addb9e6bb7
- [ ] 1575934 (Update IPC for this?)
- [ ] https://reddit.com/r/waterfox/comments/dorwpc/cannot_log_into_my_bank_account_with_new_waterfox/
- [ ] Add YouTube override
- [ ] Update NSS library to esr60 + security patches from esr68
- [ ] https://www.reddit.com/r/waterfox/comments/hjtd3o/ubp_ebanking_site_unusable_with_waterfox_classic/fxpk6u9/?context=3
- [ ] https://www.reddit.com/r/waterfox/comments/bwyxkf/single_clicking_youtube_video_sometimes_makes_it

### Waterfox Current

- [x] Separate out australis theme
- [x] Fix loading of all NPAPI plugins

### Features to keep
Issues that are planning to be deprecated by Mozilla, but will be kept by Waterfox

- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1589607

**ALREADY FIXED / NOT AN ISSUE ANYMORE:**

- [x] Global menu patch fails to merge https://github.com/MrAlex94/Waterfox/issues/350
- [x] Resource leak https://github.com/MrAlex94/Waterfox/issues/235
- [x] Zoom-in and Zoom-out cursors don't display https://github.com/MrAlex94/Waterfox/issues/347
- [x] Native ALSA support https://github.com/MrAlex94/Waterfox/issues/464
- [x] Dark theme issue with blue URL text https://github.com/MrAlex94/Waterfox/issues/282
- [x] Invisible scrollbars on macOS 10.13 High Sierra https://github.com/MrAlex94/Waterfox/issues/482
- [x] Memory issues, tabs getting delazified https://github.com/MrAlex94/Waterfox/issues/423
- [x] Customize not working https://github.com/MrAlex94/Waterfox/issues/416
- [x] Bookmarks followed by separators lose descriptions upon HTML import #564 
- [x] Ubuntu 17.04 mozconfig redirection error https://github.com/MrAlex94/Waterfox/issues/227
- [x] Global menu patch fails to merge https://github.com/MrAlex94/Waterfox/issues/350
- [x] Plugin update check no longer brings up any results https://github.com/MrAlex94/Waterfox/issues/357

**Comment by Squall-Leonhart** [comment]
> This is a new meta-issue tracker, as unfortunately GitHub does not allow changing ownership of issues.

It does though, its just in a not so obvious  location

**Comment by Peacock365** [comment]
@MrAlex94 @hawkeye116477 @oceanlantern 

**IMPORTANT UI-breaking bug on the Mac:** When the tab position "below address bar" or "bottom" is selected in the settings, the close / minimize / maximize buttons are no longer visible. Waterfox Current 2020.07.1, macOS 10.15.6 Catalina.

**Comment by hawkeye116477** [comment]
@Peacock365 I don't have Mac, so I can't help.

**Comment by Squall-Leonhart** [comment]
not sure why 1419264 is in the tracker, its always been an nvidia driver issue and long been fixed.
